config/routes.rb
Rails.application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get  '/home'         => "customers#index"
  get  '/chart'        => "pages#daily_chart"
  get  '/cityledger'   => "bill_containers#unpaid"
  get  '/billchart'    => "pages#bill_chart"
  get  'bin'           => "pages#bin"
  get  'admin' => "pages#admin"

  root   'customers#index'

  resources :users
  resources :room_categories
  resources :sessions
  
  resources :reservations
  resources :customers
  resources :rooms
  resources :customer_rooms
  resources :book_rooms
  resources :bill_containers
  resources :bills

  resources :rooms do 
    resources :customer_rooms
  end 	

  resources :customers do 
  	resources :book_rooms
    resources :bill_containers
  end 

  resources :bill_containers do 
    resources :bills
  end   
  	
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :bill_containers
	has_many :book_rooms, :dependent => :destroy
	has_many :rooms
	validates_uniqueness_of :first_name, scope: :last_name
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :phone_number, presence: true
	validates :email, presence: true, uniqueness: true 
	validates :sex, presence: true
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	def self.desc_order
		order("created_at DESC")
	end 
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customer = Customer.new

    # Search Customer query
    @search = Customer.ransack(params[:q])
    @c = @search.result(distinct: true).desc_order.limit(4).includes(:book_rooms, :bill_containers)

    @recent_bills = BillContainer.where(rollback: nil, paid: false).includes(:bills).desc_order

    # Get all Room Categories
    @room_types = RoomCategory.all

    @customers = Customer.all

    # Limit bookings and bills queries to 10
    @recent_bookings = BookRoom.where(rollback: nil, checked_out: false).desc_order

    # require 'pry'; binding.pry
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_url, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone_number, :sex, :avatar, :email, :book_rooms_attributes => [:id, :checked_out])
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_bill_search.html.erb
<%= search_form_for @search, :html => {:class => "form-inline center"} do |f| %>
    <div class="form-group">
    <%= f.label :created_at_gteq, "Day" %>
    <%= f.date_field :created_at_gteq, class: 'form-control form-inline input-sm myform', 'datepicker' => true %>
	<%= f.submit "\u2315", class: "form-control" %>
	</div>
<% end %><br>

app/views/customers/_daily_search.html.erb
<%= search_form_for @search, :html => {:class => "form-inline center"} do |f| %>
    <div class="form-group">
    <%= f.label :created_at_gteq, "Day" %>
    <%= f.date_field :created_at_gteq, class: 'form-control form-inline input-sm myform', 'datepicker' => true %>
	<%= f.submit "\u2315", class: "form-control" %>
	</div>
<% end %><br>

app/views/customers/_form.html.erb
<div class="container">
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :first_name, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-3">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :last_name, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-3">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :phone_number, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-3">
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :email, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-3">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :sex, class: "col-xs-2 col-form-label" %>
    <div class="col-xs-3">
      <%= f.select :sex, {'m' => "male", 'f' => "female"}%>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label "Passport datapage", class: "col-xs-2 col-form-label" %>
    <div class="col-xs-3">
      <%= f.file_field :avatar %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/customers/_search_form_bills.html.erb
<%= search_form_for @search1, :html => {:class => "form-inline"} do |f| %>
	<div class="form-group">
		<%= f.label :name_cont, "sex", class: "sr-only" %>
		<%= f.search_field :name_cont, class: "form-control", placeholder: "Room number" %>
	</div>
	<div class="form-group">
		<%= f.submit "\u2315", class: "form-control"  %>
	</div>
<% end %>

app/views/customers/_search_form_book.html.erb
<%= search_form_for @search2, :html => {:class => "form-inline center"} do |f| %>
	<div class="form-group">
	<%= f.label :room_number_cont, "sex", class: "sr-only" %>
	<%= f.search_field :room_number_cont, class: "form-control", placeholder: "Room number" %>
	</div>
	<div class="form-group">
	<%= f.submit "\u2315", class: "form-control"  %>
	</div>
<% end %>

app/views/customers/_search_form_cust.html.erb
<%= search_form_for @search, :html => {:class => "form-inline center"} do |f| %>
	<div class="form-group">
	<%= f.label :first_name_cont, "First name", class: "sr-only" %>
	<%= f.search_field :first_name_or_last_name_or_phone_number_cont, class: "form-control", placeholder: "Search for customer here... " %>
	</div>
	<div class="form-group">
	<%= f.submit "\u2315", class: "form-control"  %>
	</div>
<% end %>

app/views/customers/admin.html.erb
<li>
  <%= link_to "Room type", room_categories_path %>
</li>
<li>
  <%= link_to "Rooms", rooms_path %>
</li>
<li> 
  <%= link_to "Customers", customers_path %>
</li>
<li> 
  <%= link_to "All Bookings", book_rooms_path %>
</li>
<li> 
  <%= link_to "All Bills", bill_containers_path %>
</li>


<h1>Unicode Icons</h1>

&#8358; - naira

<h4>C/C++/Java source code: </h4>
Edit "\u270E" ---> <%= "\u270E" %><br>
Back "\u2190" ---> <%= "\u2190" %><br>
Submit "\u27A1" ---> <%= "\u27A1" %><br>
False "\u274C" ---> <%= "\u274C" %><br>
False black "\u2717" ---> <%= "\u2717" %><br>
True "\u2713" ---> <%= "\u2713" %><br>

app/views/customers/bill_chart.html.erb
<%= render "bill_search" %>
<div class="col-md-12 paper-box">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Room</th>
      <th>Deposit</th>
      <th>Credit</th>
      <th>Balance</th>
      <th>Paid</th>
      <th>In</th>
      <th>Out</th>
      <th colspan="3"></th>
    </tr>   
  <tbody>
    <% @bill_conts.each do |b| %>
    <% if b.rollback == nil %>
    <tr>
      <td><%= b.customer_first_name %> <%= b.customer_last_name %></td>
      <td><%= b.name %></td>
      <% @deposit = b.bills.sum(:deposit) %>
      <% @credit = b.bills.sum(:bill_price) %>
      <% @balance = @deposit - @credit %>
      <td><%= @deposit %> </td>
      <td><%= @credit %> </td>
      <td><%= @balance %></td>
      <td><%= b.paid? ? "\u2713" : "\u2717" %></td>
      <td><%= b.created_at.strftime("%d %b. %y") %></td>
      <td><%= (b.created_at + b.bills.first.days.days).strftime("%d %b.") %></td>
      <td><%= link_to 'Open', bill_container_path(b), class: "btn btn-primary btn-xs" %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>  
  </thead>
</table>
</div>

app/views/customers/daily_chart.html.erb
<%= render "daily_search" %>
<div class="col-md-12 paper-box">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Room/s </th>
      <th>Days</th>
      <th>Total</th>
      <th>Disc</th>
      <th>Stat</th>
      <th>Lodged</th>
      <th>Out</th>
      <th>Checked Out</th>
      <th colspan="3"></th>
    </tr>   
  <tbody>
    <% @book_rooms.each do |b| %>
    <% if b.rollback == nil %>
      <tr>
        <td><%= b.customer_first_name %> <%= b.customer_last_name %></td>
        <td><%= b.phone_number %></td>
        <td><%= b.room_number %> <%= b.room_no2 %> <%= b.room_no3 %> <%= b.room_no4 %> <%= b.room_no5 %> <%= b.room_no6 %> <%= b.room_no7 %> <%= b.room_no8 %> <%= b.room_no9 %> <%= b.room_no10 %> <%= b.room_no11 %> <%= b.room_no12 %> <%= b.room_no13 %> <%= b.room_no14 %> <%= b.room_no15 %> <%= b.room_no16 %> <%= b.room_no17 %> <%= b.room_no18 %> <%= b.room_no19 %> <%= b.room_no20 %> <%= b.room_no21 %> <%= b.room_no22 %> <%= b.room_no23 %> <%= b.room_no24 %> <%= b.room_no25 %> <%= b.room_no26 %> <%= b.room_no27 %>
          <%= b.room_no28 %> <%= b.room_no29 %> <%= b.room_no30 %> 
        </td>
        <td><%= b.days %></td>
        <td><%= b.total %></td>
        <td><%= b.disc_amount %></td>
        <td><%= b.checked_out? ? "\u2717" : "\u2713" %></td>
        <% if b.midnight ==  nil %>
        <td><%= b.created_at.strftime("%d %b. %Y. %H : %M")%></td>
        <% elsif b.midnight == true %>
        <td style="color:red"><%= b.created_at.strftime("%d %b. %Y. %H : %M") %> md </td>
        <% end %>
        <td><%= (b.created_at + b.days.days).strftime("%d %b.") %></td>
        <% if b.checked_out == true %>
        <td><%= b.updated_at.strftime("%d %b. %Y. %H : %M") %></td>
        <% elsif b.checked_out == false %>
        <td> in </td>
        <% end %>
        <td><%= link_to "Open", customer_path(b.customer_id), class: "btn btn-primary btn-xs" %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>  
  </thead>
</table>
</div>

app/views/customers/dirty_rooms.html.erb
<% @rooms.each do |r| %>

<% end %>

app/views/customers/edit.html.erb
<div class="col-md-8 paper-box box-middle">
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to "\u2190", customers_path %>
</div>

app/views/customers/new.html.erb
<div class="col-md-8 paper-box">
<h1>Add New Customer</h1>
</div>
<div class="col-md-8 paper-box">
<%= render 'form', customer: @customer %>
<%= link_to "\u2190", customers_path %>
</div>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
    <div class="col-md-12 paper-box">
	    <div class="col-md-2">	
	    <a type="button" data-toggle="modal" data-target="#myModala">
	    	<% if @customer.sex == 'female' %>
			<%= image_tag "img-female", size: "136x130"%>
			<% elsif @customer.sex == 'male' %>
			<%= image_tag "img-male", size: "136x130"%>
			<% end %>
		</a>
		</div>
		<div id="myModala" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		<div class="modal-dialog">
		  <div class="modal-content">
		    <div class="modal-header">
		      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		      <h4 class="modal-title" id="myModalLabel">
				<%= image_tag @customer.avatar.url(:medium) %>
				<%= image_tag @customer.avatar.url(:thumb) %>
		      </h4>
		    </div>
		    <div class="container">
		     
		    </div>
		    <div class="modal-footer">
		    </div>
		  </div>
		</div>
		</div>
		<div class="col-md-6">
			<p><strong>Name:</strong>
			  <%= @customer.first_name %> <%= @customer.last_name %></p>
			<p><strong>Phone number:</strong>
			  <%= @customer.phone_number %></p>
			<p><strong>Sex:</strong>
			  <%= @customer.sex %></p>
			<p>
			  <%= link_to "\u270E", edit_customer_path(@customer) %></p>
			<p><%= link_to "\u2190", customers_path %>
			</p>
		</div>
	</div>
	<div id="myModalz" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog">
	  <div class="modal-content">
	    <div class="container">
	      <button id="button2"  class="btn btn-default btn-xs">2nd room</button><br>
	      <button id="button3"  class="btn btn-default btn-xs">3rd room</button><br>
	      <button id="button4"  class="btn btn-default btn-xs">4th room</button><br>
	      <button id="button5"  class="btn btn-default btn-xs">5th room</button><br>
	      <button id="button6"  class="btn btn-default btn-xs">6th room</button><br>
	      <button id="button7"  class="btn btn-default btn-xs">7th room</button><br>
	      <button id="button8"  class="btn btn-default btn-xs">8th room</button><br>
	      <button id="button9"  class="btn btn-default btn-xs">9th room</button><br>
	      <button id="button10"  class="btn btn-default btn-xs">10th room</button><br>
	    </div>
	  </div>
	</div>
	</div>
	<div id="hola" class="book-room-dialog">
		<%= form_for [@customer, @customer.book_rooms.build] do |f| %>
			<% @room = Room.all %>
			<div id="container">
				<div class="form-group row" style="margin-top:20px">
				  <%= f.label "Room: ", class: "col-xs-2 col-form-label"%>
				  <div class="col-xs-1">
				    <%= f.select(:room, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room") %><br>
				  </div>
			    <a type="button" style="margin-left:80px" class="btn btn-default btn-xs" data-toggle="modal" data-target="#myModalz">
					Book more rooms 
				</a>
				<a type="button" class="btn btn-info btn-xs" data-toggle="modal" data-target="#myModal20">
					Available rooms 
				</a>
				<script>
					$("#button2").click(function () {
					  $(this).prop('disabled', true);
					  $("#container").append('<div class="form-group row" style="margin-top:20px"><%= f.label "Room2: ", class: "col-xs-2 col-form-label"%><div class="col-xs-1"><%=escape_javascript( f.select(:room2, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room")) %><br></div></div>');
					  return false;
					});
					$("#button3").click(function () {
					  $(this).prop('disabled', true);
					  $("#container").append('<div class="form-group row" style="margin-top:20px"><%= f.label "Room3: ", class: "col-xs-2 col-form-label"%><div class="col-xs-1"><%=escape_javascript( f.select(:room3, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room")) %><br></div></div>');
					  return false;
					});
					$("#button4").click(function () {
					  $(this).prop('disabled', true);
					  $("#container").append('<div class="form-group row" style="margin-top:20px"><%= f.label "Room4: ", class: "col-xs-2 col-form-label"%><div class="col-xs-1"><%=escape_javascript( f.select(:room4, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room")) %><br></div></div>');
					  return false;
					});
					$("#button5").click(function () {
					  $(this).prop('disabled', true);
					  $("#container").append('<div class="form-group row" style="margin-top:20px"><%= f.label "Room5: ", class: "col-xs-2 col-form-label"%><div class="col-xs-1"><%=escape_javascript( f.select(:room5, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room")) %><br></div></div>');
					  return false;
					});
					$("#button6").click(function () {
					  $(this).prop('disabled', true);
					  $("#container").append('<div class="form-group row" style="margin-top:20px"><%= f.label "Room6: ", class: "col-xs-2 col-form-label"%><div class="col-xs-1"><%=escape_javascript( f.select(:room6, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room")) %><br></div></div>');
					  return false;
					});
					$("#button7").click(function () {
					  $(this).prop('disabled', true);
					  $("#container").append('<div class="form-group row" style="margin-top:20px"><%= f.label "Room7: ", class: "col-xs-2 col-form-label"%><div class="col-xs-1"><%=escape_javascript( f.select(:room7, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room")) %><br></div></div>');
					  return false;
					});
					$("#button8").click(function () {
					  $(this).prop('disabled', true);
					  $("#container").append('<div class="form-group row" style="margin-top:20px"><%= f.label "Room8: ", class: "col-xs-2 col-form-label"%><div class="col-xs-1"><%=escape_javascript( f.select(:room8, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room")) %><br></div></div>');
					  return false;
					});
					$("#button9").click(function () {
					  $(this).prop('disabled', true);
					  $("#container").append('<div class="form-group row" style="margin-top:20px"><%= f.label "Room9: ", class: "col-xs-2 col-form-label"%><div class="col-xs-1"><%=escape_javascript( f.select(:room9, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room")) %><br></div></div>');
					  return false;
					});
					$("#button10").click(function () {
					  $(this).prop('disabled', true);
					  $("#container").append('<div class="form-group row" style="margin-top:20px"><%= f.label "Room10: ", class: "col-xs-2 col-form-label"%><div class="col-xs-1"><%=escape_javascript( f.select(:room10, @room.collect { |a| [a.room_number, a.id] }, :prompt => "Select room")) %><br></div></div>');
					  return false;
					});
				</script>
			    </div>
		    </div>
		    <div class="form-group row">
			  <%= f.label :days, class: "col-xs-2 col-form-label" %>
			  <div class="col-xs-3">
			    <%= f.number_field :days, class: "form-control" %><br>
			  </div>  
		    </div>
		    <div class="form-group row">
			  <%= f.label :discount, class: "col-xs-2 col-form-label" %>
			  <div class="col-xs-3">
			    <%= f.check_box :discount, class: "form-control" %><br>
			  </div>  
		    </div>
		    <div class="form-group row">
			  <%= f.label "Discount amount", class: "col-xs-2 col-form-label" %>
			  <div class="col-xs-3">
			    <%= f.number_field :disc_amount, class: "form-control" %><br>
			  </div>  
		    </div>	
		    <div class="form-group row">
			  <%= f.label "midnight?", class: "col-xs-2 col-form-label" %>
			  <div class="col-xs-3">
			    <%= f.check_box :midnight, class: "form-control" %><br>
			  </div>  
		    </div>	
		    <%= f.submit "Submit", class: "btn btn-primary" %>
		<% end %>	    
	</div>
	<div id="myModal20" class="modal fade">
	<div class="modal-dialog">
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	      <h4 class="modal-title" id="myModalLabel">Available Rooms</h4>
	    </div>
	    <div class="container">
	      <% @rooms = Room.all %>	
	      <% @rooms.each do |d| %>
	      <% if d.availability == true && d.neatness == true && d.faulty == true %>
	        Room: <%= link_to d.room_number, room_path(d) %> : Type: <%= d.room_category.name %> | Faulty <br>
	      <% elsif d.availability == true && d.neatness == true %>
	        Room: <%= link_to d.room_number, room_path(d) %> : Type: <%= d.room_category.name %><br>
	      <% end %>
	      <% end %>
	    </div>
	    <div class="modal-footer">
	    </div>
	  </div>
	</div>
	</div>
	<div class="col-md-6">
		<div class="col-md-12" style="margin-bottom:10px">
			<button id="button-toggle" type="button" class="btn btn-primary btn-lg">
		      Book Room
		    </button>
		</div>	
	</div>	

	<div class="col-md-12 paper-box">
		<div class="col-md-6">
		<table class="table table-hover">
		  <thead>
		    <tr>
		      <th>Room</th>
		      <th>Status</th>
		      <th>Days</th>
		      <th>In</th>
		      <th>Out</th>
		    </tr>   
		  <tbody>
		    <% @customer.book_rooms.where(checked_out: false).each do |b| %>
		    <tr>
		      <% if b.checked_out == true %>
		      	<td><%= link_to b.room_number, room_path(b.room) %></td>
		        <td><%= b.checked_out? ? "\u2717" : "\u2713" %></td>
		        <td><%= b.days %></td>
		        <td><%= b.created_at.strftime("%d %b. %y") %></td>
		        <td><%= (b.created_at + b.days.days).strftime("%d %b.") %></td>
		        <td><%= b.updated_at.strftime("%d %b. %y") %></td>
		        <td> <span style="color:green; font-style:italic">Checked out</span> </td>
		      <% elsif b.rollback == true %>
		        <td><%= link_to b.room_number, room_path(b.room) %></td>
		        <td><span style="color:red; font-style:italic">Rolled back</span></td>
		        <td><%= b.created_at.strftime("%d %b. %y") %></td>
		        <td><%= (b.created_at + b.days.days).strftime("%d %b.") %></td>
		        <td></td>
		        <td><span style="color:red; font-style:italic">Rolled back</span></td>
		      <% else %>  
		      	<td><%= link_to b.room_number, room_path(b.room) %></td>
		        <td><%= b.checked_out? ? "\u2717" : "\u2713" %></td>
		        <td><%= b.days %></td>
		        <td><%= b.created_at.strftime("%d %b. %y") %></td>
		        <td><%= (b.created_at + b.days.days).strftime("%d %b.") %></td>
		        <td></td>
		        <td>
		            <%= form_for b do |f| %>
		              <%= f.hidden_field :checked_out, value: true %>
		              <%= f.submit 'Checkout', class: 'btn btn-danger btn-xs' %>
		            <% end %>
		        </td>
		        <td>
		        	<%= link_to '', [b.customer, b], method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash" %>
		        </td>
		      <% end %>
		    </tr>
		    <% end %>
		  </tbody>  
		  </thead>
		</table>
		</div>

		<div class="col-md-6">
			<table class="table table-hover">
			  <thead>
			    <tr>
			      <th>Room number</th>
			      <th>Status</th>
			      <th>Date</th>
			      <th></th>
			    </tr>   
			  <tbody>
			    <% @customer.bill_containers.where(paid: false).each do |b| %>
			    <tr>
			      <td><%= b.name %></td>
			      <td><%= b.paid? ? "\u2713" : "\u2717" %></td>
			      <td><%= b.created_at.strftime("%d %b. %Y") %></td>
			      <td><%= link_to 'Open', bill_container_path(b), class: "btn btn-primary btn-xs" %></td>
			      <td><%= link_to '', [b.customer, b], method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash" %></td>
			    </tr>
			    <% end %>
			  </tbody>  
			  </thead>
			</table>
		</div>
	</div>

	<script type="text/javascript">
		$("#hola").hide();
		$("#button-toggle").click(function(){
			$("#hola").toggle();
		});
	</script>