config/routes.rb
Rails.application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  get  '/home'         => "customers#index"
  get  '/chart'        => "pages#daily_chart"
  get  '/cityledger'   => "bill_containers#unpaid"
  get  '/billchart'    => "pages#bill_chart"
  get  'bin'           => "pages#bin"
  get  'admin' => "pages#admin"

  root   'customers#index'

  resources :users
  resources :room_categories
  resources :sessions
  
  resources :reservations
  resources :customers
  resources :rooms
  resources :customer_rooms
  resources :book_rooms
  resources :bill_containers
  resources :bills

  resources :rooms do 
    resources :customer_rooms
  end 	

  resources :customers do 
  	resources :book_rooms
    resources :bill_containers
  end 

  resources :bill_containers do 
    resources :bills
  end   
  	
end

app/models/room_category.rb
class RoomCategory < ApplicationRecord
	has_many :rooms
end

app/controllers/room_categories_controller.rb
class RoomCategoriesController < ApplicationController
  before_action :set_room_category, only: [:show, :edit, :update, :destroy]

  # GET /room_categories
  # GET /room_categories.json
  def index
    @room_categories = RoomCategory.all
  end

  # GET /room_categories/1
  # GET /room_categories/1.json
  def show
  end

  # GET /room_categories/new
  def new
    @room_category = RoomCategory.new
  end

  # GET /room_categories/1/edit
  def edit
  end

  # POST /room_categories
  # POST /room_categories.json
  def create
    @room_category = RoomCategory.new(room_category_params)

    respond_to do |format|
      if @room_category.save
        format.html { redirect_to @room_category, notice: 'Room category was successfully created.' }
        format.json { render :show, status: :created, location: @room_category }
      else
        format.html { render :new }
        format.json { render json: @room_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_categories/1
  # PATCH/PUT /room_categories/1.json
  def update
    respond_to do |format|
      if @room_category.update(room_category_params)
        format.html { redirect_to @room_category, notice: 'Room category was successfully updated.' }
        format.json { render :show, status: :ok, location: @room_category }
      else
        format.html { render :edit }
        format.json { render json: @room_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_categories/1
  # DELETE /room_categories/1.json
  def destroy
    @room_category.destroy
    respond_to do |format|
      format.html { redirect_to room_categories_url, notice: 'Room category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_category
      @room_category = RoomCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_category_params
      params.require(:room_category).permit(:name, :price)
    end
end

app/helpers/room_categories_helper.rb
module RoomCategoriesHelper
end

app/views/room_categories/_form.html.erb
<%= form_for(room_category) do |f| %>
  <% if room_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room_category.errors.count, "error") %> prohibited this room_category from being saved:</h2>

      <ul>
      <% room_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/room_categories/edit.html.erb
<h1>Editing Room Category</h1>

<%= render 'form', room_category: @room_category %>

<%= link_to 'Show', @room_category %> |
<%= link_to 'Back', room_categories_path %>

app/views/room_categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-8 paper-box">
<h1>Room Categories</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price &#8358;</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_categories.each do |room_category| %>
      <tr>
        <td><%= room_category.name %></td>
        <td><%= room_category.price %></td>
        <td><%= link_to 'Show', room_category, class: "btn btn-primary btn-xs" %></td>
        <td><%= link_to "\u270E", edit_room_category_path(room_category) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room Category', new_room_category_path %>
</div>

app/views/room_categories/new.html.erb
<h1>New Room Category</h1>

<%= render 'form', room_category: @room_category %>

<%= link_to 'Back', room_categories_path %>

app/views/room_categories/show.html.erb
<div class="col-md-8 paper-box">
<p id="notice"><%= notice %></p>
<div class="col-md-3">
  <% if @room_category.name == "Standard room" %>
  <%= image_tag "standard-room", size: "136x130" %>
  <% elsif @room_category.name == "Executive room" %>
  <%= image_tag "executive-room", size: "136x130" %>
  <% elsif @room_category.name == "Executive Luxury" %>
  <%= image_tag "executive-room", size: "136x130" %>
  <% elsif @room_category.name == "Royal Room" %>
  <%= image_tag "royal-room", size: "136x130" %>
  <% elsif @room_category.name == "Royal Plus" %>
  <%= image_tag "royal-plus", size: "136x130" %>
  <% elsif @room_category.name == "Executive Suite" %>
  <%= image_tag "executive-suite", size: "136x130" %>
  <% elsif @room_category.name == "Royal Suite" %>
  <%= image_tag "royal-suite", size: "136x130" %>
  <% elsif @room_category.name == "Presidential Suite" %>
  <%= image_tag "presidential-suite", size: "136x130" %>
  <% end  %>
</div>
<div class="col-md-6">
  <div class="room-desc-container">
    <p>
      <strong>Name:</strong>
      <%= @room_category.name %>
    </p>

    <p>
      <strong>Price:</strong>
      &#8358; <%= @room_category.price %>
    </p>
    <%= link_to "\u270E", edit_room_category_path(@room_category) %><br>
    <%= link_to "\u2190", room_categories_path %>
    </div>
  </div>
</div>

<div class="col-md-12 paper-box">
<% @room_category.rooms.each do |room| %>
	<%= link_to room_path(room) do  %>
<% if room.availability == false %>
<div class="room-box box-red">
  <%= room.room_number %></br>
  <% if room.neatness == false %>
  <div class="neat-border border-red">
  </div>
  <% elsif room.neatness == true %>
  <div class="neat-border border-green">
  </div>
  <% end %>
</div>
<% elsif room.availability == true %>
<div class="room-box box-green">
  <%= room.room_number %></br>
  <% if room.neatness == false %>
  <div class="neat-border border-red">
  </div>
  <% elsif room.neatness == true %>
  <div class="neat-border border-green">
  </div>
  <% end %>
</div>
<% end %>
<% end %>
<% end %>
</div>